'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7LeVbTBqASu
 */
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { SyntheticEvent, useState } from 'react';
import axios from 'axios';

export function CreateModal() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleModal = () => {
    setIsOpen(!isOpen);
  };

  const handleSubmit = async (e: SyntheticEvent): Promise<void> => {
    e.preventDefault();

    const target = e.target as typeof e.target & {
      contents: { value: string };
    };

    await axios('http://0.0.0.0:8000/todo', {
      method: 'put',
      data: { contents: target.contents.value },
    });
  };

  return (
    <>
      <Button className='bg-black text-white' onClick={toggleModal}>
        Add New Task
      </Button>
      {isOpen && (
        <div className='ma fixed top-0 left-0 flex items-center justify-center w-full h-full bg-black bg-opacity-50 z-0'>
          <Card className='mx-auto my-4 p-4 w-[80vw] max-w-[500px] bg-white'>
            <CardHeader>
              <CardTitle className='text-2xl font-bold'>New Todo Item</CardTitle>
            </CardHeader>
            <CardContent>
              <form className='space-y-4' onSubmit={handleSubmit}>
                <div className='flex flex-col space-y-2'>
                  <Label htmlFor='todo-title'>Todo</Label>
                  <Input id='todo-title' placeholder='Enter the todo' name='contents' />
                </div>
                <div className='flex justify-end'>
                  <Button onClick={toggleModal}>close</Button>
                  <Button className='w-32' type='submit'>
                    Submit Todo
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>
      )}
    </>
  );
}
